import {Router} from "express";
import userRouter from "../userRoutes.js";
import bikeRouter from "../bikeRoutes.js";
import maintenanceRouter from "../maintenanceRecordRoutes.js";
import serviceBookingRouter from "../serviceBookingRoutes.js";
import sparePartRouter from "../sparePartRoutes.js";
import additionalServiceRouter from "../additionalServiceRoutes.js";
import invoiceRouter from "../invoiceRoutes.js";
import servicePackageRouter from "../servicePackageRoutes.js";
import serviceReportRouter from "../serviceReportRoutes.js";
import serviceRequestRouter from "../serviceRequestRoutes.js";
import serviceSlotRouter from "../serviceSlotRoutes.js";
import serviceUpdateRouter from "../serviceUpdateRoutes.js";
import authRouter from "../authenticationRoute.js";
const allRoutes = Router();
allRoutes.use(userRouter)
allRoutes.use(bikeRouter);
allRoutes.use(maintenanceRouter);
allRoutes.use(serviceBookingRouter);
allRoutes.use(sparePartRouter);
allRoutes.use(additionalServiceRouter);
allRoutes.use(invoiceRouter);
allRoutes.use(servicePackageRouter);
allRoutes.use(serviceReportRouter);
allRoutes.use(serviceRequestRouter);
allRoutes.use(serviceSlotRouter);
allRoutes.use(serviceUpdateRouter);
allRoutes.use(authRouter);
export default allRoutes;